version: '3.9'

services:
  django:
    container_name: django
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ../media:/app/media
    command: uv run --no-sync python src/manage.py runserver 0.0.0.0:8000
    ports:
      - 8005:8000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:17.5
    expose:
      - 5432
    env_file: ../.env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isalready
      interval: 10s
      timeout: 3s
      retries: 3
