# Generated by Django 5.2.4 on 2025-07-10 13:10

import posts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Identifier'),
                ),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('content', posts.models.CompressedTextField(verbose_name='Content (org)')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
            },
        ),
    ]
